---
server:
  port: 8100
  contextPath: /userauth 

security:
  user:
    password: password
  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smarktool	
    username: iems
    password: iems

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

error:
  path=/error
