---
server:
  port: 8082

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/iems
    username: iems
    password: iems

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates

  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory

# Map the error path to error template (for Thymeleaf)
error:
  path=/error
