---
server:
  port: 8082

spring:
  inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
		
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.102:3306/iems
    username: iems
    password: iems

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: validate

  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates

  thymeleaf:
    cache: false             # Allow Thymeleaf templates to be reloaded at runtime
    prefix: classpath:/templates/    # Trailing / mandatory

# Map the error path to error template (for Thymeleaf)
error:
  path=/error

eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get 
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://192.168.1.102:8761/eureka/